# 这些是支持选项。取消注释以启用它们。
# github: # 用您的GitHub用户名替换
# patreon: # 用您的Patreon用户名替换
# open_collective: # 用您的Open Collective用户名替换
# ko_fi: # 用您的Ko-fi用户名替换
# tidelift: # 用您的Tidelift平台名称替换
# community_bridge: # 用您的Community Bridge项目名称替换
# liberapay: # 用您的Liberapay用户名替换
# issuehunt: # 用您的IssueHunt用户名替换
# otechie: # 用您的Otechie用户名替换
# lfx_crowdfunding: # 用您的LFX Crowdfunding项目名称替换
# polar: # 用您的Polar用户名替换
# buy_me_a_coffee: # 用您的Buy Me a Coffee用户名替换
# thanks_dev: # 用您的Thanks.dev用户名替换
# custom: # 用您的自定义URL替换

# 本项目为教学资料，暂不启用资金支持
